package guess.domain;

/**
 * Guess mode.
 */
public enum GuessMode {
    GUESS_NAME_BY_PHOTO_MODE,
    GUESS_PHOTO_BY_NAME_MODE,
    GUESS_TALK_BY_SPEAKER_MODE,
    GUESS_SPEAKER_BY_TALK_MODE,
    GUESS_ACCOUNTS_BY_SPEAKER_MODE,
    GUESS_SPEAKER_BY_ACCOUNTS_MODE
}
