package guess.domain;

/**
 * Guess mode.
 */
public enum GuessMode {
    GUESS_NAME_BY_PHOTO_MODE,
    GUESS_PHOTO_BY_NAME_MODE,
    GUESS_TALK_BY_SPEAKER_MODE,
    GUESS_SPEAKER_BY_TALK_MODE,
    GUESS_COMPANY_BY_SPEAKER_MODE,
    GUESS_SPEAKER_BY_COMPANY_MODE,
    GUESS_ACCOUNT_BY_SPEAKER_MODE,
    GUESS_SPEAKER_BY_ACCOUNT_MODE
}
