package guess.domain;

/**
 * Application state.
 */
public enum State {
    START_STATE,
    GUESS_NAME_BY_PHOTO_STATE,
    GUESS_PHOTO_BY_NAME_STATE,
    GUESS_TALK_BY_SPEAKER_STATE,
    GUESS_SPEAKER_BY_TALK_STATE,
    GUESS_ACCOUNTS_BY_SPEAKER_STATE,
    GUESS_SPEAKER_BY_ACCOUNTS_STATE,
    RESULT_STATE
}
